name = str(input("Hello. What is your name? "))
print("")
age = int(input("Hi, " + name + "! How old are you? "))
print("")
print(f"Did you know that in five years you will be {age + 5} years old?")
print(f"And five years ago you were {age - 5}! Imagine that!")